name: CI
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  build_job:
    runs-on: ubuntu-latest
  eslint_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checking code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run ESLint on backend
        run: |
          cd packages/backend
          npm run lint
      - name: Run ESLint on frontend
        run: |
          cd packages/frontend
          npm run lint
