name: CI
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install -w packages/backend
        run: npm install -w packages/frontend
      - name: Run ESLint
        run: npm run lint -w packages/backend
        run: npm run lint -w packages/frontend