name: CI
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  backend:
    name: Backend service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install packages
        working-directory: packages/backend
        run: npm ci
      - name: Linting
        working-directory: packages/backend
        run: |
          npm run lint
  frontend:
    name: Frontend service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install packages
        working-directory: packages/frontend
        run: npm ci
      - name: Linting
        working-directory: packages/frontend
        run: |
          npm run lint
        run: 
          npm run test -w frontend